### ISSUE TITLE
[v0.3] Record command getting Type exception using NormalizeObservations

### ISSUE THREAD

**Issue by joecargill** [MillionIntegrals/vel#38]
Hey,

I have been trying out Vel for a day or two now, using it with a few gym classic control environments. 

One issue I have run into is when I use the `vel configs/cartpole_dqn.yaml record` command I get the following:

```
RuntimeError: expected type torch.cuda.DoubleTensor but got torch.cuda.FloatTensor
```

I have worked around the issue by editing the `normalize_observations.py` file `register_buffer` functions to expect `dtype=torch.double` when I intend to use the Record command, and change it back to `torch.float` when I want to train, but hopefully you can figure out what is causing it as I cannot (I am a bit of newbie with PyTorch).

Here is the full stack trace:

```
Evaluating environment...
Traceback (most recent call last):
  File "/home/j/anaconda3/bin/vel", line 11, in <module>
    load_entry_point('vel', 'console_scripts', 'vel')()
  File "/home/j/dev/vel/vel/launcher.py", line 64, in main
    model_config.run_command(args.command, args.varargs)
  File "/home/j/dev/vel/vel/internals/model_config.py", line 119, in run_command
    return command_descriptor.run(*varargs)
  File "/home/j/dev/vel/vel/rl/commands/record_movie_command.py", line 43, in run
    self.record_take(model, env, device, take_number=i + 1)
  File "/home/j/anaconda3/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/j/dev/vel/vel/rl/commands/record_movie_command.py", line 68, in record_take
    actions = model.step(observation_tensor, **self.sample_args)['actions']
  File "/home/j/dev/vel/vel/rl/models/q_model.py", line 65, in step
    q_values = self(observations)
  File "/home/j/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/j/dev/vel/vel/rl/models/q_model.py", line 58, in forward
    observations = self.input_block(observations)
  File "/home/j/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/j/dev/vel/vel/modules/input/normalize_observations.py", line 48, in forward
    return (input_vector- self.running_mean.unsqueeze(0)) / torch.sqrt(self.running_var.unsqueeze(0))
RuntimeError: expected type torch.cuda.DoubleTensor but got torch.cuda.FloatTensor
```

**Comment by joecargill** [comment]
Here is my config: (please forgive any glaring errors in setup values haha)

```yaml
name: 'cartpole_dqn'


env:
  name: vel_classic_control.env.classic_control
  game: 'CartPole-v1'


vec_env:
  name: vel.rl.vecenv.dummy
  frame_history: 4


model:
  name: vel.rl.models.q_model

  input_block:
    name: vel.modules.input.normalize_observations
    input_shape: 16

  backbone:
    name: vel.rl.models.backbone.mlp
    input_length: 16
    hidden_layers: [64, 64]
    activation: 'tanh'


reinforcer:
  name: vel.rl.reinforcers.buffered_off_policy_iteration_reinforcer

  env_roller:
    name: vel.rl.env_roller.transition_replay_env_roller

    replay_buffer:
      name: vel.rl.buffers.circular_replay_buffer

      buffer_capacity: 1_000_000
      buffer_initial_size: 2_000

    action_noise:
      name: vel.rl.modules.noise.eps_greedy

      epsilon:
        name: vel.schedules.linear_and_constant
        end_of_interpolation: 0.1
        initial_value: 1.0
        final_value: 0.1

  algo:
    name: vel.rl.algo.dqn

    target_update_frequency: 10_000
    max_grad_norm: 0.5

    discount_factor: 0.99

  rollout_steps: 4
  training_steps: 32
  parallel_envs: 1


optimizer:
  name: vel.optimizers.rmsprop
  lr: 2.5e-4
  alpha: 0.95
  momentum: 0.95
  epsilon: 1.0e-1


commands:
  train:
    name: vel.rl.commands.rl_train_command
    total_frames: 3e5  
    batches_per_epoch: 2500

  record:
    name: vel.rl.commands.record_movie_command
    takes: 10
    videoname: 'cartpole_dqn_vid_{:04}.avi'

  evaluate:
    name: vel.rl.commands.evaluate_env_command
    takes: 100
    frame_history: 4
```

**Comment by MillionIntegrals** [comment]
Hi Joe,
 
Thank you very much for your interest in vel. I'm sorry I wasn't very responsive but I had quite a few life  changes recently. 

Fix to this bug was very easy and is now pushed to the candidate branch.
